version: '2'
services:
    springmicroservice-app:
        image: springmicroservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://springmicroservice-mysql:3306/springmicroservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    springmicroservice-mysql:
        extends:
            file: mysql.yml
            service: springmicroservice-mysql
